/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg_vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class vistaPago extends javax.swing.JFrame {
    
   public vistaPago() {
    initComponents();
}
   public javax.swing.JTextField getTxtIdPago() {
    return txtIdPago;
}

public javax.swing.JTextField getTxtFechaPago() {
    return txtFechaPago;
}

public javax.swing.JTextField getTxtMontoPago() {
    return txtMontoPago;
}

public javax.swing.JTextField getTxtMetodoPago() {
    return txtMetodoPago;
}

public javax.swing.JTextField getTxtIdClientePago() {
    return txtIdClientePago;
}

public javax.swing.JButton getBtnRegistrarPago() {
    return btnRegistrarPago;
}

public javax.swing.JButton getBtnConsultarPago() {
    return btnConsultarPago;
}

public javax.swing.JButton getBtnActualizarPago() {
    return btnActualizarPago;
}

public javax.swing.JButton getBtnEliminarPago() {
    return btnEliminarPago;
}

public javax.swing.JTable getTblPago() {
    return tblPago;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPago = new javax.swing.JTable();
        lblIdPago = new javax.swing.JLabel();
        lblFechaPago = new javax.swing.JLabel();
        lblMontoPago = new javax.swing.JLabel();
        lblMetodoPago = new javax.swing.JLabel();
        lblIdClientePago = new javax.swing.JLabel();
        txtIdPago = new javax.swing.JTextField();
        txtFechaPago = new javax.swing.JTextField();
        txtMontoPago = new javax.swing.JTextField();
        txtMetodoPago = new javax.swing.JTextField();
        txtIdClientePago = new javax.swing.JTextField();
        btnRegistrarPago = new javax.swing.JButton();
        btnConsultarPago = new javax.swing.JButton();
        btnActualizarPago = new javax.swing.JButton();
        btnEliminarPago = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("PAGO");

        tblPago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "FECHA", "MONTO", "METODO", "CLIENTE"
            }
        ));
        jScrollPane1.setViewportView(tblPago);

        lblIdPago.setText("IdPago:");

        lblFechaPago.setText("FechaPago:");

        lblMontoPago.setText("Monto:");

        lblMetodoPago.setText("MetodoPago:");

        lblIdClientePago.setText("IdCliente:");

        btnRegistrarPago.setText("REGISTRAR");

        btnConsultarPago.setText("CONSULTAR");
        btnConsultarPago.addActionListener(this::btnConsultarPagoActionPerformed);

        btnActualizarPago.setText("ACTUALIZAR");

        btnEliminarPago.setText("ELIMINAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblIdClientePago)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtIdClientePago))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblMetodoPago)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMetodoPago))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblMontoPago)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtMontoPago))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblFechaPago)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFechaPago))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblIdPago)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtIdPago, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnRegistrarPago)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                        .addComponent(btnConsultarPago))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnActualizarPago)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnEliminarPago)))))))
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdPago)
                            .addComponent(txtIdPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrarPago)
                            .addComponent(btnConsultarPago))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaPago)
                            .addComponent(txtFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblMontoPago))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMontoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnActualizarPago)
                        .addComponent(btnEliminarPago)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMetodoPago)
                    .addComponent(txtMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdClientePago)
                    .addComponent(txtIdClientePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarPagoActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizarPago;
    public javax.swing.JButton btnConsultarPago;
    public javax.swing.JButton btnEliminarPago;
    public javax.swing.JButton btnRegistrarPago;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblFechaPago;
    public javax.swing.JLabel lblIdClientePago;
    public javax.swing.JLabel lblIdPago;
    public javax.swing.JLabel lblMetodoPago;
    private javax.swing.JLabel lblMontoPago;
    public javax.swing.JTable tblPago;
    public javax.swing.JTextField txtFechaPago;
    public javax.swing.JTextField txtIdClientePago;
    public javax.swing.JTextField txtIdPago;
    public javax.swing.JTextField txtMetodoPago;
    public javax.swing.JTextField txtMontoPago;
    // End of variables declaration//GEN-END:variables
}
